# Generated by Django 3.1.4 on 2020-12-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailData',
        ),
    ]
